// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.BackEnd.UserManager;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>UserSearch</b><br>
 * Generated     : <b>2021/03/09 下午5:46:49</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  3月 09, 2021
 * @author zhangyu
 */
public abstract class UserSearchHelper extends RationalTestScript
{
	/**
	 * htmlBrowser： with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_IE() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_IE"));
	}
	/**
	 * htmlBrowser： with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_IE(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_IE"), anchor, flags);
	}
	
	/**
	 * 重置button： with default state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : 重 置
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject button_Reset() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_Reset"));
	}
	/**
	 * 重置button： with specific test context and state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : 重 置
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject button_Reset(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_Reset"), anchor, flags);
	}
	
	/**
	 * 查询button： with default state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : 查 询
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_search() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_search"));
	}
	/**
	 * 查询button： with specific test context and state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : 查 询
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_search(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_search"), anchor, flags);
	}
	
	/**
	 * HtmlINPUTCheckbox： with default state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_select() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_select"));
	}
	/**
	 * HtmlINPUTCheckbox： with specific test context and state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_select(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_select"), anchor, flags);
	}
	
	/**
	 * HtmlINPUTText： with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_keyword() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_keyword"));
	}
	/**
	 * HtmlINPUTText： with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_keyword(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_keyword"), anchor, flags);
	}
	
	

	protected UserSearchHelper()
	{
		setScriptName("BackEnd.UserManager.UserSearch");
	}
	
}

