// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.BackEnd.Basic;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>CloudReady</b><br>
 * Generated     : <b>2021/03/16 ÏÂÎç2:25:36</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  3ÔÂ 16, 2021
 * @author zhangyu
 */
public abstract class CloudReadyHelper extends RationalTestScript
{
	/**
	 * febs£º with default state.
	 *		.id : febs
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_febs() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_febs"));
	}
	/**
	 * febs£º with specific test context and state.
	 *		.id : febs
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_febs(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_febs"), anchor, flags);
	}
	
	/**
	 * ÔÆ¶Ë¾ÍÐ÷£º with default state.
	 *		.text : ÔÆ¶Ë¾ÍÐ÷
	 * 		.href : javascript:void(0)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 5
	 */
	protected GuiTestObject link_CloudReady() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_CloudReady"));
	}
	/**
	 * ÔÆ¶Ë¾ÍÐ÷£º with specific test context and state.
	 *		.text : ÔÆ¶Ë¾ÍÐ÷
	 * 		.href : javascript:void(0)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 5
	 */
	protected GuiTestObject link_CloudReady(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_CloudReady"), anchor, flags);
	}
	
	

	protected CloudReadyHelper()
	{
		setScriptName("BackEnd.Basic.CloudReady");
	}
	
}

