// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.BackEnd.Basic;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Logout</b><br>
 * Generated     : <b>2021/03/09 下午4:49:14</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  3月 09, 2021
 * @author zhangyu
 */
public abstract class LogoutHelper extends RationalTestScript
{
	/**
	 * htmlBrowser： with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_IE() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_IE"));
	}
	/**
	 * htmlBrowser： with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_IE(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_IE"), anchor, flags);
	}
	
	/**
	 * 雄安IPv6发展监测平台后台管理系统： with default state.
	 *		.title : 雄安IPv6发展监测平台-后台管理系统
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://121.37.191.78:8088/adminView/#/login
	 */
	protected DocumentTestObject document_IPv6() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_IPv6"));
	}
	/**
	 * 雄安IPv6发展监测平台后台管理系统： with specific test context and state.
	 *		.title : 雄安IPv6发展监测平台-后台管理系统
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://121.37.191.78:8088/adminView/#/login
	 */
	protected DocumentTestObject document_IPv6(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_IPv6"), anchor, flags);
	}
	
	/**
	 * febs： with default state.
	 *		.id : febs
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_febs() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_febs"));
	}
	/**
	 * febs： with specific test context and state.
	 *		.id : febs
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_febs(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_febs"), anchor, flags);
	}
	
	

	protected LogoutHelper()
	{
		setScriptName("BackEnd.Basic.Logout");
	}
	
}

