// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.BackEnd.Basic;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Refresh</b><br>
 * Generated     : <b>2021/03/16 上午10:50:59</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  3月 16, 2021
 * @author zhangyu
 */
public abstract class RefreshHelper extends RationalTestScript
{
	/**
	 * 雄安IPv6发展监测平台： with default state.
	 *		.text : 雄安IPv6发展监测平台
	 * 		.href : #/
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_Refresh() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_Refresh"));
	}
	/**
	 * 雄安IPv6发展监测平台： with specific test context and state.
	 *		.text : 雄安IPv6发展监测平台
	 * 		.href : #/
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_Refresh(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_Refresh"), anchor, flags);
	}
	
	

	protected RefreshHelper()
	{
		setScriptName("BackEnd.Basic.Refresh");
	}
	
}

